name: "[PUSH] Create Package"
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "force-app/**"
      - "exp-cloud/**"
jobs:
  create-package:
    name: Run Package Creation
    uses: fluidfoslex/sf-workflows/.github/workflows/packageCreate.yml@main
    permissions:
      contents: write
    secrets: inherit
